### ISSUE TITLE
cloning ERROR

### ISSUE THREAD

**Issue by maku0** [sunplus-plus1/linux#1]
Hi, while I'm trying to clone this repo I've got error:
git.exe clone --progress -v "https://github.com/sunplus-plus1/linux.git" "C:\_soft\sunplus\linux"
Cloning into 'C:\_soft\sunplus\linux'...

POST git-upload-pack (152 bytes)
POST git-upload-pack (190 bytes)
remote: Enumerating objects: 431, done.
remote: Counting objects: 100% (431/431), done.
remote: Compressing objects: 100% (333/333), done.
remote: Total 66914 (delta 107), reused 323 (delta 97), pack-reused 66483
Receiving objects: 100% (66914/66914), 183.20 MiB | 19.59 MiB/s, done.
Resolving deltas: 100% (5325/5325), done.
error: invalid path 'drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
git did not exit cleanly (exit code 128) (12078 ms @ 28.05.2020 14:34:20)

**Comment by sunplus-plus1** [comment]
Hi maku0,
I just try to create prefix 'aux' file on win7, then it failed. It seem have special use on Windows. so please run on ubuntu or like mention that you can run 'git restore --source=HEAD :/' in "C:_soft\sunplus\linux", git will clone all except prefix 'aux' file then you must create aux.x as other file name by manual.
